# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Refresh TimeTable

on:
  workflow_dispatch:
  
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  # everyday at 00:00
  schedule:
    - cron: '0 0 * * *'

  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.6"

    
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v2.2.2
      # with:
      #   chromedriver-version: "130.0.6723.91"

    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: run mainCode
      run: |
        python ./main.py

    - name: commit
      run: |
        git config --global user.email calRobot@github.com
        git config --global user.name githubAction
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

  # 在这里修改学期代码，用逗号分隔
  TERM: "2502,2506"
